### ISSUE TITLE
Text is not selected on toggling finder

### ISSUE THREAD

**Issue by pvorona** [viddo/recent-files-fuzzy-finder#16]
1. Open finder
2. Type something and close it (esc by default)
3. Open finder again. Previously typed text still there and its very nice. Finder acts like this text is selected wich is also amazing. But the text itself is displayed without selection background wich is wrong.
   I'm using One-Dark theme

**Comment by viddo** [comment]
The behavior is the same one as for https://github.com/atom/fuzzy-finder actually, I'm just [extending the `FuzzyFinderView`](https://github.com/viddo/recent-files-fuzzy-finder/blob/master/lib/recent-files-view.coffee#L6) to have a different use a different set of items. For consistency with the default fuzzy-finder windows, and minimize long-term maintainability, I would rather not change any behavior here. If you feel strongly for this change I'd suggest to direct your request to the [official repo](https://github.com/atom/fuzzy-finder) instead.

The 3rd point sounds like a bug? Again, since I'm just [extending the `FuzzyFinderView`](https://github.com/viddo/recent-files-fuzzy-finder/blob/master/lib/recent-files-view.coffee#L6) there's no custom styles or things done here to set any colors. That sounds like an issue you should address on the repo of [that theme](https://github.com/atom/one-dark-ui) instead.
