### ISSUE TITLE
Enhancement: Allow to remove items from the recent-files list?

### ISSUE THREAD

**Issue by well1791** [viddo/recent-files-fuzzy-finder#24]
Hi!

I'm really grateful for this plugin! It's really helpful and productive!

I was wondering if it's possible to add this feature to the current behavior, as this is possible using Jetbrains's recent-files.

So just to refine the expected behavior I wrote a short description:
_If the query-search is empty and the user press `backspace` then removes that item just from the list. If the removed item is currently opened in a tab, the file won't be closed._

Btw, I was trying to open a PR instead of an issue but, I didn't understand the code.
So, if you agree on adding this feature I would gladly spend more time researching atom's API to open a proper PR.

Thanks!

**Comment by viddo** [comment]
Hi there!
Love to hear that you're grateful for the plugin, it brings me great joy knowing that a small plugin like this can be helpful and make people more productive. ^_^

It does sound like a useful feature indeed, I wasn't aware of it (haven't used Jetbrain's editors in years). More than happy to accept a PR for the behavior you're describing! Like mentioned in the [contributing file](https://github.com/viddo/recent-files-fuzzy-finder/blob/master/CONTRIBUTING.md), please add some test cases to have the feature covered. It makes it easier to maintain this plugin and makes sure the functionality when code changes in the future.

Re: implementation and in particular the comment _I didn't understand the code_. What part(s) specifically did you have a hard time understanding? Is there some way I can make it easier for you to implement this?

Thanks to you!

**Comment by well1791** [comment]
Hey, it's nice that you agree in the feature ^^

I was searching through the code but, I think it's not quite simple to implement it the way it's right now.

The idea I had in mind was to read the query-search, if it's empty and the user press `del` then I remove the currently selected item from the `recent-files` list.
To do that I need a key-up event-listener to read the key-code.

Right now [`recent-files`](https://github.com/viddo/recent-files-fuzzy-finder/blob/master/lib/recent-files-view.js#L8) depends on [`fuzzy-finder`](https://github.com/atom/fuzzy-finder/blob/master/lib/fuzzy-finder-view.js#L13) and that one depends on [`atom-select-list`](https://github.com/atom/fuzzy-finder/blob/master/lib/fuzzy-finder-view.js#L17).
It's atom-select-list which [sets the event-listeners](https://github.com/atom/atom-select-list/blob/master/src/select-list-view.js#L325-L342) but, there's no `key-up` event, they use [this](https://github.com/atom/atom-select-list/blob/master/src/select-list-view.js#L200) to get the query-string.

So, that's what I've got ):

**Comment by viddo** [comment]
Sounds like you've got the correct high-level approach. 

The dependency chain can be problematic as you noticed, but I don't think it's a blocker for this feature. 
Side note: I actually did a PR (https://github.com/atom/fuzzy-finder/pull/132) to have this be included in the native `fuzzy-finder` plugin instead of having to do this plugin in the first place.

Either way, like I just mentioned I believe these are solvable:
- You don't need or actually want to map on any key-up event. Atom has it's own system to manage key input, see [KeymapManager](https://atom.io/docs/api/v1.20.1/KeymapManager) and [Keymaps in depth](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/). Once you read the official docs this code piece should make sense https://github.com/atom/atom-select-list/blob/33b2252589891c9fa14a2ea4b91cee6b71df4764/src/select-list-view.js#L45-L72 you probably want a listener for `core:backspace`.
- The query string should be retrievable by`this.selectListView.getQuery()` from within this context: https://github.com/viddo/recent-files-fuzzy-finder/blob/4d3d0a9cb16a91c2e9969c0d667dac73275a9070/lib/recent-files-view.js#L13
