### ISSUE TITLE
the finder won't open unless Atom has at least 1 tab/ file already open

### ISSUE THREAD

**Issue by andrew-james-heard** [viddo/recent-files-fuzzy-finder#26]
I don't see the logic in this. If I close all my tabs the finder can't be made visible. As a workaround I use ctrl+shift+T to open the last opened file, then the finder works.

**Comment by viddo** [comment]
That's not on purpose, sounds like you hit a bug. 

I can't reproduce it myself though. 😕  If I open a bunch of files and then "close all my tabs" the recent view shows those closed files (as I'd expect). Can you provide some concrete steps/example of how to reproduce this?

Having a [quick look at the implementation](https://github.com/viddo/recent-files-fuzzy-finder/blob/4b0ca9b661ae0ead4f32e0198f75dca1811a6378/lib/recent-files-view.js#L29), the view is not shown if there are no "recent files" for whatever reason, so that might be what you observe (for whatever reason). Either way, probably should remove that if-check so the `getEmptyMessage` case is shown instead.

**Comment by andrew-james-heard** [comment]
Hi viddo - wow, that was a quick response. To reproduce:

1 have 1 tab open
2 alt-t --> recent-files window is opened, press Esc
3 close the 1 open tab
4 alt-t --> recent-files window is not opened

More than happy to try any package update. I'm only a new atom user so you'll need to give some instructions where to put any new package. I'm using 64-bit Windows 10.

>the view is not shown if there are no "recent files"

hmm not sure because ctrl+shift+T (reopen last item) works when all tabs are closed

**Comment by viddo** [comment]
> To reproduce:
> 1 have 1 tab open
> 2 alt-t --> recent-files window is opened, press Esc
> 3 close the 1 open tab
> 4 alt-t --> recent-files window is not opened

What file did you see in step 2? What did you do prior to step 1 to get to that single tab open?

There must be something that differs between our scenarios because I get a different result: 
- Prior to all steps I opened Atom of a project folder without having any open files and then open a file of that project (so I have that 1 tab open as in step 1)
- On step 2 the window is opened, because I have no recent files yet.
- On step 4 the window is opened, and shows the file of the just-closed tab.

> hmm not sure because ctrl+shift+T (reopen last item) works when all tabs are closed

That feature is not part of this package so that's unrelated.

I'll release a new version that will always show the window (with empty message if there are no recent files) once the CI of #27 is green.

**Comment by andrew-james-heard** [comment]
>What file did you see in step 2?
a TXT or a PY file, nothing special about it though, just whatever the last file I closed was

>What did you do prior to step 1 to get to that single tab open?
again nothing special; I opened atom from the start menu & it restored the single file that had been open when last exited; or from Explorer context menu "open as" a text file with atom

>That feature is not part of this package so that's unrelated.
no, it was just a convenient way of opening a single tab

Probably best I just wait now rather than waste anymore of your time. It will be interesting to see the new behavior.

**Comment by viddo** [comment]
Thanks for the additional info, I'll look into if I reproduce doing something similar to that (I'm on Mac so slightly different startup ways I guess).

Just released 0.4.0 btw, so please update and see if that helps in any way.

**Comment by andrew-james-heard** [comment]
Thanks. I just updated to 0.4.0. Same behavior.

**Comment by viddo** [comment]
Ok, I've tried the additional steps you did, but still haven't been able to
reproduce it. :( There's no platform specific logic so shouldn't be any
difference between Windows/OSX either.

Not sure how to troubleshoot this further. :/

**Comment by andrew-james-heard** [comment]
How hard would it be to build the package myself in Windows? I could maybe add some debugging/ logging statements in the area of concern in order to get some clues what is going wrong. I'm a retired C# programmer & just lately a Python dabbler but maybe worth a shot.

**Comment by viddo** [comment]
Yeah, that shouldn't be too hard then. To get started:
- clone the repo on your local computer (`git clone …` etc.)
- add `console.log`/debugger calls where you see fit
- setup the package to be used in _development mode_: `apm link -d
path\to\clone`
- start atom in development mode: `atom -d`

This would use the source code from the cloned repo instead of the installed package.
Note that you'd need to restart Atom to get any file modifications you do though, so it can be a bit of a slow process if you need to do a lot of modifications to figure out the culprit.

For additional docs on hacking Atom see the official docs of
- http://flight-manual.atom.io/hacking-atom/sections/debugging
- http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-font-rendering-issues
- http://flight-manual.atom.io/behind-atom/sections/developing-node-modules/

Hope that helps.

**Comment by andrew-james-heard** [comment]
You've been very generous with your time & support. It's not a high priority but I'll let you know how I go.
